### ISSUE TITLE
L07: Нужно попоравить положение скобочек

### ISSUE THREAD

**Issue by matry-ny** [NesterOk/skillup_php#3]
https://github.com/NesterOk/skillup_php/blob/8e168aa79cc4089e2495bfe2f1cf3dda2faf33c3/homework/2020.10.15/index.php#L71

в принте нужно поправить положение закрывающих скобок вложенных массивов

**Comment by NesterOk** [comment]
Сделал перенос открывающимся скобкам и сделал отступы закрывающимся и открывающимся скобкам вложенных массивов.
